export const GET_STORE_SUCCESS = "GET_STORE_SUCCESS";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const CHANGE_MINIMUM_VALUE = "CHANGE_MINIMUM_VALUE";
export const FILTER_STORES = "FILTER_STORES";
export const SORTED_TABLE_VALUE = "SORTED_TABLE_VALUE";
export const SORTED_TABLE_BY_NAME = "SORTED_TABLE_BY_NAME";
export const FILTER_STORES_ON_MAP = "FILTER_STORES_ON_MAP";